x-service-names:
  - &service1 iris_1
  - &service2 iris_2
  - &service3 iris_3

networks:
  my_custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
    driver_opts:
      com.docker.network.bridge.name: iris

services:
  iris-classifier_1:
    image: theurbanpenguin/iris_classifier
    container_name: *service1
    hostname: *service1
    restart: unless-stopped
    networks:
      my_custom_network:

  iris-classifier_2:
    image: theurbanpenguin/iris_classifier
    container_name: *service2
    hostname: *service2
    restart: unless-stopped
    networks:
      my_custom_network:

  iris-classifier_3:
    image: theurbanpenguin/iris_classifier
    container_name: *service3
    hostname: *service3
    restart: unless-stopped
    networks:
      my_custom_network:

  load_balancer:
    image: theurbanpenguin/nginx_lb
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    networks:
      my_custom_network:
    ports:
      - "8080:80"